<?php

use Illuminate\Database\Seeder;

class UserActionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'roles', 'action_id' => 1,],
            ['id' => 2, 'user_id' => 1, 'action' => 'created', 'action_model' => 'timeshifts', 'action_id' => 1,],
            ['id' => 3, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'users', 'action_id' => 1,],
            ['id' => 4, 'user_id' => 1, 'action' => 'created', 'action_model' => 'employees', 'action_id' => 1,],
            ['id' => 5, 'user_id' => 1, 'action' => 'created', 'action_model' => 'leaveperiods', 'action_id' => 1,],
            ['id' => 6, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'employees', 'action_id' => 1,],
            ['id' => 7, 'user_id' => 1, 'action' => 'created', 'action_model' => 'entitlementsleaves', 'action_id' => 1,],
            ['id' => 8, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'entitlementsleaves', 'action_id' => 1,],
            ['id' => 9, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'entitlementsleaves', 'action_id' => 1,],
            ['id' => 10, 'user_id' => 1, 'action' => 'created', 'action_model' => 'entitlementsleaves', 'action_id' => 2,],
            ['id' => 11, 'user_id' => 1, 'action' => 'created', 'action_model' => 'leaveentitlements', 'action_id' => 1,],
            ['id' => 12, 'user_id' => 1, 'action' => 'created', 'action_model' => 'leaveentitlements', 'action_id' => 2,],
            ['id' => 13, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'leaveentitlements', 'action_id' => 2,],
            ['id' => 14, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'leaveentitlements', 'action_id' => 1,],
            ['id' => 15, 'user_id' => 1, 'action' => 'created', 'action_model' => 'jobs', 'action_id' => 1,],
            ['id' => 16, 'user_id' => 1, 'action' => 'created', 'action_model' => 'salaries', 'action_id' => 1,],
            ['id' => 17, 'user_id' => 1, 'action' => 'created', 'action_model' => 'vacancies', 'action_id' => 1,],
            ['id' => 18, 'user_id' => 1, 'action' => 'created', 'action_model' => 'disciplineactions', 'action_id' => 1,],
            ['id' => 19, 'user_id' => 1, 'action' => 'created', 'action_model' => 'disciplineactions', 'action_id' => 2,],
            ['id' => 20, 'user_id' => 1, 'action' => 'created', 'action_model' => 'disciplineactions', 'action_id' => 3,],
            ['id' => 21, 'user_id' => 1, 'action' => 'created', 'action_model' => 'disciplineactions', 'action_id' => 4,],
            ['id' => 22, 'user_id' => 1, 'action' => 'created', 'action_model' => 'disciplinarycases', 'action_id' => 1,],
            ['id' => 23, 'user_id' => 1, 'action' => 'created', 'action_model' => 'statuses', 'action_id' => 1,],
            ['id' => 24, 'user_id' => 1, 'action' => 'created', 'action_model' => 'leaveentitlements', 'action_id' => 1,],
            ['id' => 25, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'leaveentitlements', 'action_id' => 1,],
            ['id' => 26, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'leaveentitlements', 'action_id' => 1,],
            ['id' => 27, 'user_id' => 1, 'action' => 'created', 'action_model' => 'users', 'action_id' => 2,],
            ['id' => 28, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'leaveentitlements', 'action_id' => 1,],
            ['id' => 29, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'users', 'action_id' => 2,],
            ['id' => 30, 'user_id' => 1, 'action' => 'created', 'action_model' => 'leaveentitlements', 'action_id' => 1,],
            ['id' => 31, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'leaveentitlements', 'action_id' => 1,],
            ['id' => 32, 'user_id' => 1, 'action' => 'created', 'action_model' => 'roles', 'action_id' => 3,],
            ['id' => 33, 'user_id' => 1, 'action' => 'created', 'action_model' => 'users', 'action_id' => 3,],
            ['id' => 34, 'user_id' => 1, 'action' => 'created', 'action_model' => 'jobs', 'action_id' => 2,],
            ['id' => 35, 'user_id' => 1, 'action' => 'created', 'action_model' => 'costcenters', 'action_id' => 1,],
            ['id' => 36, 'user_id' => 1, 'action' => 'created', 'action_model' => 'skills', 'action_id' => 1,],
            ['id' => 37, 'user_id' => 1, 'action' => 'created', 'action_model' => 'education', 'action_id' => 1,],
            ['id' => 38, 'user_id' => 1, 'action' => 'created', 'action_model' => 'nationalities', 'action_id' => 1,],
            ['id' => 39, 'user_id' => 1, 'action' => 'created', 'action_model' => 'currencies', 'action_id' => 1,],
            ['id' => 40, 'user_id' => 1, 'action' => 'created', 'action_model' => 'salaries', 'action_id' => 2,],
            ['id' => 41, 'user_id' => 1, 'action' => 'created', 'action_model' => 'employees', 'action_id' => 2,],
            ['id' => 42, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'roles', 'action_id' => 2,],
            ['id' => 43, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'roles', 'action_id' => 3,],
            ['id' => 44, 'user_id' => 1, 'action' => 'created', 'action_model' => 'roles', 'action_id' => 4,],
            ['id' => 45, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'roles', 'action_id' => 1,],
            ['id' => 46, 'user_id' => 1, 'action' => 'created', 'action_model' => 'roles', 'action_id' => 5,],
            ['id' => 47, 'user_id' => 1, 'action' => 'created', 'action_model' => 'roles', 'action_id' => 6,],
            ['id' => 48, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'jobs', 'action_id' => 1,],
            ['id' => 49, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'jobs', 'action_id' => 2,],
            ['id' => 50, 'user_id' => 1, 'action' => 'created', 'action_model' => 'jobs', 'action_id' => 3,],
            ['id' => 51, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'jobs', 'action_id' => 3,],
            ['id' => 52, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'employees', 'action_id' => 1,],
            ['id' => 53, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'employees', 'action_id' => 2,],
            ['id' => 54, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'salaries', 'action_id' => 1,],
            ['id' => 55, 'user_id' => 1, 'action' => 'created', 'action_model' => 'salaries', 'action_id' => 3,],
            ['id' => 56, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'salaries', 'action_id' => 3,],
            ['id' => 57, 'user_id' => 1, 'action' => 'created', 'action_model' => 'employees', 'action_id' => 3,],
            ['id' => 58, 'user_id' => 1, 'action' => 'created', 'action_model' => 'contact_companies', 'action_id' => 1,],
            ['id' => 59, 'user_id' => 1, 'action' => 'created', 'action_model' => 'contact_companies', 'action_id' => 2,],
            ['id' => 60, 'user_id' => 1, 'action' => 'created', 'action_model' => 'contacts', 'action_id' => 1,],
            ['id' => 61, 'user_id' => 1, 'action' => 'created', 'action_model' => 'contacts', 'action_id' => 2,],
            ['id' => 62, 'user_id' => 1, 'action' => 'created', 'action_model' => 'expense_categories', 'action_id' => 1,],
            ['id' => 63, 'user_id' => 1, 'action' => 'created', 'action_model' => 'expense_categories', 'action_id' => 2,],
            ['id' => 64, 'user_id' => 1, 'action' => 'created', 'action_model' => 'expense_categories', 'action_id' => 3,],
            ['id' => 65, 'user_id' => 1, 'action' => 'created', 'action_model' => 'expense_categories', 'action_id' => 4,],
            ['id' => 66, 'user_id' => 1, 'action' => 'created', 'action_model' => 'expense_categories', 'action_id' => 5,],
            ['id' => 67, 'user_id' => 1, 'action' => 'created', 'action_model' => 'income_categories', 'action_id' => 1,],
            ['id' => 68, 'user_id' => 1, 'action' => 'created', 'action_model' => 'income_categories', 'action_id' => 2,],
            ['id' => 69, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'income_categories', 'action_id' => 1,],
            ['id' => 70, 'user_id' => 1, 'action' => 'created', 'action_model' => 'expense_categories', 'action_id' => 6,],
            ['id' => 71, 'user_id' => 1, 'action' => 'created', 'action_model' => 'incomes', 'action_id' => 1,],
            ['id' => 72, 'user_id' => 1, 'action' => 'created', 'action_model' => 'incomes', 'action_id' => 2,],
            ['id' => 73, 'user_id' => 1, 'action' => 'created', 'action_model' => 'expenses', 'action_id' => 1,],
            ['id' => 74, 'user_id' => 1, 'action' => 'created', 'action_model' => 'expenses', 'action_id' => 2,],
            ['id' => 75, 'user_id' => 1, 'action' => 'created', 'action_model' => 'assets_categories', 'action_id' => 1,],
            ['id' => 76, 'user_id' => 1, 'action' => 'created', 'action_model' => 'assets_categories', 'action_id' => 2,],
            ['id' => 77, 'user_id' => 1, 'action' => 'created', 'action_model' => 'assets_categories', 'action_id' => 3,],
            ['id' => 78, 'user_id' => 1, 'action' => 'created', 'action_model' => 'assets_categories', 'action_id' => 4,],
            ['id' => 79, 'user_id' => 1, 'action' => 'created', 'action_model' => 'assets_categories', 'action_id' => 5,],
            ['id' => 80, 'user_id' => 1, 'action' => 'created', 'action_model' => 'assets_locations', 'action_id' => 1,],
            ['id' => 81, 'user_id' => 1, 'action' => 'created', 'action_model' => 'assets_locations', 'action_id' => 2,],
            ['id' => 82, 'user_id' => 1, 'action' => 'created', 'action_model' => 'assets_locations', 'action_id' => 3,],
            ['id' => 83, 'user_id' => 1, 'action' => 'created', 'action_model' => 'assets', 'action_id' => 1,],
            ['id' => 84, 'user_id' => 1, 'action' => 'created', 'action_model' => 'assets', 'action_id' => 2,],
            ['id' => 85, 'user_id' => 1, 'action' => 'updated', 'action_model' => 'employees', 'action_id' => 3,],
            ['id' => 86, 'user_id' => 1, 'action' => 'created', 'action_model' => 'leaveentitlements', 'action_id' => 2,],
            ['id' => 87, 'user_id' => 1, 'action' => 'created', 'action_model' => 'employees', 'action_id' => 4,],
            ['id' => 88, 'user_id' => 1, 'action' => 'created', 'action_model' => 'calendars', 'action_id' => 1,],
            ['id' => 89, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'users', 'action_id' => 3,],
            ['id' => 90, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'timeshifts', 'action_id' => 1,],
            ['id' => 91, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'employees', 'action_id' => 3,],
            ['id' => 92, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'employees', 'action_id' => 4,],
            ['id' => 93, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'calendars', 'action_id' => 1,],
            ['id' => 94, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'incomes', 'action_id' => 1,],
            ['id' => 95, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'incomes', 'action_id' => 2,],
            ['id' => 96, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'expenses', 'action_id' => 1,],
            ['id' => 97, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'expenses', 'action_id' => 2,],
            ['id' => 98, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'contacts', 'action_id' => 1,],
            ['id' => 99, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'contacts', 'action_id' => 2,],
            ['id' => 100, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'assets', 'action_id' => 1,],
            ['id' => 101, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'assets', 'action_id' => 2,],
            ['id' => 102, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'leaveentitlements', 'action_id' => 2,],
            ['id' => 103, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'vacancies', 'action_id' => 1,],
            ['id' => 104, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'disciplinarycases', 'action_id' => 1,],
            ['id' => 105, 'user_id' => 1, 'action' => 'created', 'action_model' => 'employees', 'action_id' => 5,],
            ['id' => 106, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'employees', 'action_id' => 5,],
            ['id' => 107, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'jobs', 'action_id' => 3,],
            ['id' => 108, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'costcenters', 'action_id' => 1,],
            ['id' => 109, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'skills', 'action_id' => 1,],
            ['id' => 110, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'salaries', 'action_id' => 2,],
            ['id' => 111, 'user_id' => 1, 'action' => 'deleted', 'action_model' => 'salaries', 'action_id' => 3,],

        ];

        foreach ($items as $item) {
            \App\UserAction::create($item);
        }
    }
}
