<?php
Route::get('/', function () { return view('welcome'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::get('/reports/employees-stats', 'Admin\ReportsController@employeesStats');
    Route::get('/reports/contact-stats', 'Admin\ReportsController@contactStats');
    Route::get('/reports/asset-stats', 'Admin\ReportsController@assetStats');
    Route::get('/reports/job-candidates', 'Admin\ReportsController@jobCandidates');

    Route::get('/calendar', 'Admin\SystemCalendarController@index');

    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('courses', 'Admin\CoursesController');
    Route::post('courses_mass_destroy', ['uses' => 'Admin\CoursesController@massDestroy', 'as' => 'courses.mass_destroy']);
    Route::post('courses_restore/{id}', ['uses' => 'Admin\CoursesController@restore', 'as' => 'courses.restore']);
    Route::delete('courses_perma_del/{id}', ['uses' => 'Admin\CoursesController@perma_del', 'as' => 'courses.perma_del']);
    Route::resource('organization_charts', 'Admin\OrganizationChartsController');
    Route::resource('contact_companies', 'Admin\ContactCompaniesController');
    Route::post('contact_companies_mass_destroy', ['uses' => 'Admin\ContactCompaniesController@massDestroy', 'as' => 'contact_companies.mass_destroy']);
    Route::resource('expense_categories', 'Admin\ExpenseCategoriesController');
    Route::post('expense_categories_mass_destroy', ['uses' => 'Admin\ExpenseCategoriesController@massDestroy', 'as' => 'expense_categories.mass_destroy']);
    Route::resource('assets', 'Admin\AssetsController');
    Route::post('assets_mass_destroy', ['uses' => 'Admin\AssetsController@massDestroy', 'as' => 'assets.mass_destroy']);
    Route::resource('leaveperiods', 'Admin\LeaveperiodsController');
    Route::post('leaveperiods_mass_destroy', ['uses' => 'Admin\LeaveperiodsController@massDestroy', 'as' => 'leaveperiods.mass_destroy']);
    Route::post('leaveperiods_restore/{id}', ['uses' => 'Admin\LeaveperiodsController@restore', 'as' => 'leaveperiods.restore']);
    Route::delete('leaveperiods_perma_del/{id}', ['uses' => 'Admin\LeaveperiodsController@perma_del', 'as' => 'leaveperiods.perma_del']);
    Route::resource('vacancies', 'Admin\VacanciesController');
    Route::post('vacancies_mass_destroy', ['uses' => 'Admin\VacanciesController@massDestroy', 'as' => 'vacancies.mass_destroy']);
    Route::post('vacancies_restore/{id}', ['uses' => 'Admin\VacanciesController@restore', 'as' => 'vacancies.restore']);
    Route::delete('vacancies_perma_del/{id}', ['uses' => 'Admin\VacanciesController@perma_del', 'as' => 'vacancies.perma_del']);
    Route::resource('disciplineactions', 'Admin\DisciplineactionsController');
    Route::post('disciplineactions_mass_destroy', ['uses' => 'Admin\DisciplineactionsController@massDestroy', 'as' => 'disciplineactions.mass_destroy']);
    Route::post('disciplineactions_restore/{id}', ['uses' => 'Admin\DisciplineactionsController@restore', 'as' => 'disciplineactions.restore']);
    Route::delete('disciplineactions_perma_del/{id}', ['uses' => 'Admin\DisciplineactionsController@perma_del', 'as' => 'disciplineactions.perma_del']);
    Route::resource('personals', 'Admin\PersonalsController');
    Route::resource('selfprofessionals', 'Admin\SelfprofessionalsController');
    Route::post('selfprofessionals_mass_destroy', ['uses' => 'Admin\SelfprofessionalsController@massDestroy', 'as' => 'selfprofessionals.mass_destroy']);
    Route::post('selfprofessionals_restore/{id}', ['uses' => 'Admin\SelfprofessionalsController@restore', 'as' => 'selfprofessionals.restore']);
    Route::delete('selfprofessionals_perma_del/{id}', ['uses' => 'Admin\SelfprofessionalsController@perma_del', 'as' => 'selfprofessionals.perma_del']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('recruitmentoffers', 'Admin\RecruitmentoffersController');
    Route::post('recruitmentoffers_mass_destroy', ['uses' => 'Admin\RecruitmentoffersController@massDestroy', 'as' => 'recruitmentoffers.mass_destroy']);
    Route::post('recruitmentoffers_restore/{id}', ['uses' => 'Admin\RecruitmentoffersController@restore', 'as' => 'recruitmentoffers.restore']);
    Route::delete('recruitmentoffers_perma_del/{id}', ['uses' => 'Admin\RecruitmentoffersController@perma_del', 'as' => 'recruitmentoffers.perma_del']);
    Route::resource('games', 'Admin\GamesController');
    Route::resource('leaveentitlements', 'Admin\LeaveentitlementsController');
    Route::post('leaveentitlements_mass_destroy', ['uses' => 'Admin\LeaveentitlementsController@massDestroy', 'as' => 'leaveentitlements.mass_destroy']);
    Route::post('leaveentitlements_restore/{id}', ['uses' => 'Admin\LeaveentitlementsController@restore', 'as' => 'leaveentitlements.restore']);
    Route::delete('leaveentitlements_perma_del/{id}', ['uses' => 'Admin\LeaveentitlementsController@perma_del', 'as' => 'leaveentitlements.perma_del']);
    Route::resource('contacts', 'Admin\ContactsController');
    Route::post('contacts_mass_destroy', ['uses' => 'Admin\ContactsController@massDestroy', 'as' => 'contacts.mass_destroy']);
    Route::resource('income_categories', 'Admin\IncomeCategoriesController');
    Route::post('income_categories_mass_destroy', ['uses' => 'Admin\IncomeCategoriesController@massDestroy', 'as' => 'income_categories.mass_destroy']);
    Route::resource('assets_categories', 'Admin\AssetsCategoriesController');
    Route::post('assets_categories_mass_destroy', ['uses' => 'Admin\AssetsCategoriesController@massDestroy', 'as' => 'assets_categories.mass_destroy']);
    Route::resource('disciplinarycases', 'Admin\DisciplinarycasesController');
    Route::post('disciplinarycases_mass_destroy', ['uses' => 'Admin\DisciplinarycasesController@massDestroy', 'as' => 'disciplinarycases.mass_destroy']);
    Route::post('disciplinarycases_restore/{id}', ['uses' => 'Admin\DisciplinarycasesController@restore', 'as' => 'disciplinarycases.restore']);
    Route::delete('disciplinarycases_perma_del/{id}', ['uses' => 'Admin\DisciplinarycasesController@perma_del', 'as' => 'disciplinarycases.perma_del']);
    Route::resource('noticias', 'Admin\NoticiasController');
    Route::resource('self_certificates', 'Admin\SelfCertificatesController');
    Route::resource('awards', 'Admin\AwardsController');
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('incomes', 'Admin\IncomesController');
    Route::post('incomes_mass_destroy', ['uses' => 'Admin\IncomesController@massDestroy', 'as' => 'incomes.mass_destroy']);
    Route::resource('assets_locations', 'Admin\AssetsLocationsController');
    Route::post('assets_locations_mass_destroy', ['uses' => 'Admin\AssetsLocationsController@massDestroy', 'as' => 'assets_locations.mass_destroy']);
    Route::resource('candidates', 'Admin\CandidatesController');
    Route::post('candidates_mass_destroy', ['uses' => 'Admin\CandidatesController@massDestroy', 'as' => 'candidates.mass_destroy']);
    Route::post('candidates_restore/{id}', ['uses' => 'Admin\CandidatesController@restore', 'as' => 'candidates.restore']);
    Route::delete('candidates_perma_del/{id}', ['uses' => 'Admin\CandidatesController@perma_del', 'as' => 'candidates.perma_del']);
    Route::resource('self_vacations', 'Admin\SelfVacationsController');
    Route::resource('aptitudes', 'Admin\AptitudesController');
    Route::resource('expenses', 'Admin\ExpensesController');
    Route::post('expenses_mass_destroy', ['uses' => 'Admin\ExpensesController@massDestroy', 'as' => 'expenses.mass_destroy']);
    Route::resource('assets_statuses', 'Admin\AssetsStatusesController');
    Route::post('assets_statuses_mass_destroy', ['uses' => 'Admin\AssetsStatusesController@massDestroy', 'as' => 'assets_statuses.mass_destroy']);
    Route::resource('news', 'Admin\NewsController');
    Route::post('news_mass_destroy', ['uses' => 'Admin\NewsController@massDestroy', 'as' => 'news.mass_destroy']);
    Route::post('news_restore/{id}', ['uses' => 'Admin\NewsController@restore', 'as' => 'news.restore']);
    Route::delete('news_perma_del/{id}', ['uses' => 'Admin\NewsController@perma_del', 'as' => 'news.perma_del']);
    Route::resource('selfdocuments', 'Admin\SelfdocumentsController');
    Route::post('selfdocuments_mass_destroy', ['uses' => 'Admin\SelfdocumentsController@massDestroy', 'as' => 'selfdocuments.mass_destroy']);
    Route::post('selfdocuments_restore/{id}', ['uses' => 'Admin\SelfdocumentsController@restore', 'as' => 'selfdocuments.restore']);
    Route::delete('selfdocuments_perma_del/{id}', ['uses' => 'Admin\SelfdocumentsController@perma_del', 'as' => 'selfdocuments.perma_del']);
    Route::resource('monthly_reports', 'Admin\MonthlyReportsController');
    Route::resource('assets_histories', 'Admin\AssetsHistoriesController');
    Route::resource('employees', 'Admin\EmployeesController');
    Route::post('employees_mass_destroy', ['uses' => 'Admin\EmployeesController@massDestroy', 'as' => 'employees.mass_destroy']);
    Route::post('employees_restore/{id}', ['uses' => 'Admin\EmployeesController@restore', 'as' => 'employees.restore']);
    Route::delete('employees_perma_del/{id}', ['uses' => 'Admin\EmployeesController@perma_del', 'as' => 'employees.perma_del']);
    Route::resource('calendars', 'Admin\CalendarsController');
    Route::post('calendars_mass_destroy', ['uses' => 'Admin\CalendarsController@massDestroy', 'as' => 'calendars.mass_destroy']);
    Route::post('calendars_restore/{id}', ['uses' => 'Admin\CalendarsController@restore', 'as' => 'calendars.restore']);
    Route::delete('calendars_perma_del/{id}', ['uses' => 'Admin\CalendarsController@perma_del', 'as' => 'calendars.perma_del']);
    Route::resource('jobs', 'Admin\JobsController');
    Route::post('jobs_mass_destroy', ['uses' => 'Admin\JobsController@massDestroy', 'as' => 'jobs.mass_destroy']);
    Route::post('jobs_restore/{id}', ['uses' => 'Admin\JobsController@restore', 'as' => 'jobs.restore']);
    Route::delete('jobs_perma_del/{id}', ['uses' => 'Admin\JobsController@perma_del', 'as' => 'jobs.perma_del']);
    Route::resource('timeshifts', 'Admin\TimeshiftsController');
    Route::post('timeshifts_mass_destroy', ['uses' => 'Admin\TimeshiftsController@massDestroy', 'as' => 'timeshifts.mass_destroy']);
    Route::post('timeshifts_restore/{id}', ['uses' => 'Admin\TimeshiftsController@restore', 'as' => 'timeshifts.restore']);
    Route::delete('timeshifts_perma_del/{id}', ['uses' => 'Admin\TimeshiftsController@perma_del', 'as' => 'timeshifts.perma_del']);
    Route::resource('costcenters', 'Admin\CostcentersController');
    Route::post('costcenters_mass_destroy', ['uses' => 'Admin\CostcentersController@massDestroy', 'as' => 'costcenters.mass_destroy']);
    Route::post('costcenters_restore/{id}', ['uses' => 'Admin\CostcentersController@restore', 'as' => 'costcenters.restore']);
    Route::delete('costcenters_perma_del/{id}', ['uses' => 'Admin\CostcentersController@perma_del', 'as' => 'costcenters.perma_del']);
    Route::resource('skills', 'Admin\SkillsController');
    Route::post('skills_mass_destroy', ['uses' => 'Admin\SkillsController@massDestroy', 'as' => 'skills.mass_destroy']);
    Route::post('skills_restore/{id}', ['uses' => 'Admin\SkillsController@restore', 'as' => 'skills.restore']);
    Route::delete('skills_perma_del/{id}', ['uses' => 'Admin\SkillsController@perma_del', 'as' => 'skills.perma_del']);
    Route::resource('education', 'Admin\EducationController');
    Route::post('education_mass_destroy', ['uses' => 'Admin\EducationController@massDestroy', 'as' => 'education.mass_destroy']);
    Route::post('education_restore/{id}', ['uses' => 'Admin\EducationController@restore', 'as' => 'education.restore']);
    Route::delete('education_perma_del/{id}', ['uses' => 'Admin\EducationController@perma_del', 'as' => 'education.perma_del']);
    Route::resource('nationalities', 'Admin\NationalitiesController');
    Route::post('nationalities_mass_destroy', ['uses' => 'Admin\NationalitiesController@massDestroy', 'as' => 'nationalities.mass_destroy']);
    Route::post('nationalities_restore/{id}', ['uses' => 'Admin\NationalitiesController@restore', 'as' => 'nationalities.restore']);
    Route::delete('nationalities_perma_del/{id}', ['uses' => 'Admin\NationalitiesController@perma_del', 'as' => 'nationalities.perma_del']);
    Route::get('internal_notifications/read', 'Admin\InternalNotificationsController@read');
    Route::resource('internal_notifications', 'Admin\InternalNotificationsController');
    Route::post('internal_notifications_mass_destroy', ['uses' => 'Admin\InternalNotificationsController@massDestroy', 'as' => 'internal_notifications.mass_destroy']);
    Route::resource('currencies', 'Admin\CurrenciesController');
    Route::post('currencies_mass_destroy', ['uses' => 'Admin\CurrenciesController@massDestroy', 'as' => 'currencies.mass_destroy']);
    Route::post('currencies_restore/{id}', ['uses' => 'Admin\CurrenciesController@restore', 'as' => 'currencies.restore']);
    Route::delete('currencies_perma_del/{id}', ['uses' => 'Admin\CurrenciesController@perma_del', 'as' => 'currencies.perma_del']);
    Route::resource('salaries', 'Admin\SalariesController');
    Route::post('salaries_mass_destroy', ['uses' => 'Admin\SalariesController@massDestroy', 'as' => 'salaries.mass_destroy']);
    Route::post('salaries_restore/{id}', ['uses' => 'Admin\SalariesController@restore', 'as' => 'salaries.restore']);
    Route::delete('salaries_perma_del/{id}', ['uses' => 'Admin\SalariesController@perma_del', 'as' => 'salaries.perma_del']);
    Route::resource('statuses', 'Admin\StatusesController');
    Route::post('statuses_mass_destroy', ['uses' => 'Admin\StatusesController@massDestroy', 'as' => 'statuses.mass_destroy']);
    Route::post('statuses_restore/{id}', ['uses' => 'Admin\StatusesController@restore', 'as' => 'statuses.restore']);
    Route::delete('statuses_perma_del/{id}', ['uses' => 'Admin\StatusesController@perma_del', 'as' => 'statuses.perma_del']);
    Route::resource('badges', 'Admin\BadgesController');
    Route::post('badges_mass_destroy', ['uses' => 'Admin\BadgesController@massDestroy', 'as' => 'badges.mass_destroy']);
    Route::post('badges_restore/{id}', ['uses' => 'Admin\BadgesController@restore', 'as' => 'badges.restore']);
    Route::delete('badges_perma_del/{id}', ['uses' => 'Admin\BadgesController@perma_del', 'as' => 'badges.perma_del']);
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    Route::model('messenger', 'App\MessengerTopic');
    Route::get('messenger/inbox', 'Admin\MessengerController@inbox')->name('messenger.inbox');
    Route::get('messenger/outbox', 'Admin\MessengerController@outbox')->name('messenger.outbox');
    Route::resource('messenger', 'Admin\MessengerController');

    Route::post('csv_parse', 'Admin\CsvImportController@parse')->name('csv_parse');
    Route::post('csv_process', 'Admin\CsvImportController@process')->name('csv_process');

    Route::get('search', 'MegaSearchController@search')->name('mega-search');
    Route::get('language/{lang}', function ($lang) {
        return redirect()->back()->withCookie(cookie()->forever('language', $lang));
    })->name('language');});
